# -*- coding: utf-8 -*-
"""Copia de Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17utbmVZVp_6UTgcZY4mQs3eaVfgdujQm
"""

import os
from tqdm.auto import tqdm
import xml.etree.ElementTree as ET

os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
import numpy
print(numpy.__version__)
print(numpy.show_config())

import tensorflow as tf
print("TensorFlow version:", tf.__version__)
from tensorflow import keras

import keras_cv
from keras_cv import bounding_box
from keras_cv import visualization

#import tensorflow_text as text

#print(tf.__version__)
#print(text.__version__)

SPLIT_RATIO = 0.2
BATCH_SIZE = 4
LEARNING_RATE = 0.001
EPOCH = 5
GLOBAL_CLIPNORM = 10.0

class_ids = [
    "EarlyBlight",
    "LateBlight",
    "Healthy",
]
class_mapping = dict(zip(range(len(class_ids)), class_ids))

# Path to images and annotations
path_all = "D:/DATASETS/Imagenes/Solanaceas/PotatoCoco/train/"


#Extraer imagenes de 
xml_files = sorted(
    [
        os.path.join(path_all, file_name)
        for file_name in os.listdir(path_all)
        if file_name.endswith(".xml")
    ]
)

# Get all JPEG image file paths in path_images and sort them
jpg_files = sorted(
    [
        os.path.join(path_all, file_name)
        for file_name in os.listdir(path_all)
        if file_name.endswith(".jpg")
    ]
)

def parse_annotation(xml_file):
    tree = ET.parse(xml_file)
    root = tree.getroot()

    image_name = root.find("filename").text
    image_path = os.path.join(path_all, image_name)


    boxes = []
    classes = []
    for obj in root.iter("object"):
        cls = obj.find("name").text
        classes.append(cls)


        bbox = obj.find("bndbox")
        xmin = float(bbox.find("xmin").text)
        ymin = float(bbox.find("ymin").text)
        xmax = float(bbox.find("xmax").text)
        ymax = float(bbox.find("ymax").text)
        boxes.append([xmin, ymin, xmax, ymax])

    class_ids = [
        list(class_mapping.keys())[list(class_mapping.values()).index(cls)]
        for cls in classes
    ]
    return image_path, boxes, class_ids



image_paths = []
bbox = []
classes = []
for xml_file in tqdm(xml_files):
    image_path, boxes, class_ids = parse_annotation(xml_file)
    image_paths.append(image_path)
    bbox.append(boxes)
    classes.append(class_ids)


bbox = tf.ragged.constant(bbox)
classes = tf.ragged.constant(classes)
image_paths = tf.ragged.constant(image_paths)

data = tf.data.Dataset.from_tensor_slices((image_paths, classes, bbox))

# Determine the number of validation samples
num_val = int(len(xml_files) * SPLIT_RATIO)

# Split the dataset into train and validation sets
val_data = data.take(num_val)
train_data = data.skip(num_val)

batch = 2
num_boxes = 50

bounding_boxes = {
    # num_boxes may be a Ragged dimension
    'boxes': tf.zeros(shape=[batch, num_boxes, 4]),
    'classes': tf.zeros(shape=[batch, num_boxes])
}

def load_image(image_path):
    image = tf.io.read_file(image_path)
    image = tf.image.decode_jpeg(image, channels=3)
    return image


def load_dataset(image_path, classes, bbox):
    # Read Image
    image = load_image(image_path)
    bounding_boxes = {
        "classes": tf.cast(classes, dtype=tf.float32),
        "boxes": bbox,
    }
    return {"images": tf.cast(image, tf.float32), "bounding_boxes": bounding_boxes}


augmenter = keras.Sequential(
    layers=[
        keras_cv.layers.RandomFlip(mode="horizontal", bounding_box_format="xyxy"),
        keras_cv.layers.RandomShear(
            x_factor=0.2, y_factor=0.2, bounding_box_format="xyxy"
        ),
        keras_cv.layers.JitteredResize(
            target_size=(640, 640), scale_factor=(0.75, 1.3), bounding_box_format="xyxy"
        ),
    ]
)

train_ds = train_data.map(load_dataset, num_parallel_calls=tf.data.AUTOTUNE)
train_ds = train_ds.shuffle(BATCH_SIZE * 4)
train_ds = train_ds.ragged_batch(BATCH_SIZE, drop_remainder=True)
train_ds = train_ds.map(augmenter, num_parallel_calls=tf.data.AUTOTUNE)

resizing = keras_cv.layers.JitteredResize(
    target_size=(640, 640),
    scale_factor=(0.75, 1.3),
    bounding_box_format="xyxy",
)

val_ds = val_data.map(load_dataset, num_parallel_calls=tf.data.AUTOTUNE)
val_ds = val_ds.shuffle(BATCH_SIZE * 4)
val_ds = val_ds.ragged_batch(BATCH_SIZE, drop_remainder=True)
val_ds = val_ds.map(resizing, num_parallel_calls=tf.data.AUTOTUNE)

def visualize_dataset(inputs, value_range, rows, cols, bounding_box_format):
    inputs = next(iter(inputs.take(1)))
    images, bounding_boxes = inputs["images"], inputs["bounding_boxes"]
    visualization.plot_bounding_box_gallery(
        images,
        value_range=value_range,
        rows=rows,
        cols=cols,
        y_true=bounding_boxes,
        scale=5,
        font_scale=0.7,
        bounding_box_format=bounding_box_format,
        class_mapping=class_mapping,
    )


visualize_dataset(
    train_ds, bounding_box_format="xyxy", value_range=(0, 255), rows=2, cols=2
)

visualize_dataset(
    val_ds, bounding_box_format="xyxy", value_range=(0, 255), rows=2, cols=2
)

def dict_to_tuple(inputs):
    return inputs["images"], inputs["bounding_boxes"]


train_ds = train_ds.map(dict_to_tuple, num_parallel_calls=tf.data.AUTOTUNE)
train_ds = train_ds.prefetch(tf.data.AUTOTUNE)

val_ds = val_ds.map(dict_to_tuple, num_parallel_calls=tf.data.AUTOTUNE)
val_ds = val_ds.prefetch(tf.data.AUTOTUNE)

backbone = keras_cv.models.YOLOV8Backbone.from_preset(
    "yolo_v8_s_backbone_coco"  # We will use yolov8 small backbone with coco weights
)

yolo = keras_cv.models.YOLOV8Detector(
    num_classes=len(class_mapping),
    bounding_box_format="xyxy",
    backbone=backbone,
    fpn_depth=1,
)

optimizer = tf.keras.optimizers.Adam(
    learning_rate=LEARNING_RATE,
    global_clipnorm=GLOBAL_CLIPNORM,
)

yolo.compile(
    optimizer=optimizer, classification_loss="binary_crossentropy", box_loss="ciou"
)

import numpy as np

class EvaluateCOCOMetricsCallback(keras.callbacks.Callback):
    def __init__(self, data, save_path):
        super().__init__()
        self.data = data
        self.metrics = keras_cv.metrics.BoxCOCOMetrics(
            bounding_box_format="xyxy",
            evaluate_freq=1e9,
        )
        self.save_path = save_path
        self.best_map = -1.0

    def on_epoch_end(self, epoch, logs=None):
        if logs is None:
            logs = {}
        # Reset the metric state at the start of evaluation
        self.metrics.reset_state()

        # Lists to gather all boxes and classes across the batch
        all_true_boxes = []
        all_true_classes = []
        all_pred_boxes = []
        all_pred_classes = []
        all_pred_confidence = []

        for batch in self.data:
            images, y_true = batch[0], batch[1]
            y_pred = self.model.predict(images, verbose=0)

            # Extract true data
            y_true_boxes = y_true["boxes"]
            y_true_classes = y_true["classes"]
            y_pred_boxes = y_pred["boxes"]
            y_pred_classes = y_pred["classes"]
            y_pred_confidence = y_pred.get("confidence", None)

            # Convert numpy arrays to tensors if necessary
            if isinstance(y_true_boxes, np.ndarray):
                y_true_boxes = tf.convert_to_tensor(y_true_boxes)
            if isinstance(y_true_classes, np.ndarray):
                y_true_classes = tf.convert_to_tensor(y_true_classes)
            if isinstance(y_pred_boxes, np.ndarray):
                y_pred_boxes = tf.convert_to_tensor(y_pred_boxes)
            if isinstance(y_pred_classes, np.ndarray):
                y_pred_classes = tf.convert_to_tensor(y_pred_classes)
            if y_pred_confidence is not None and isinstance(y_pred_confidence, np.ndarray):
                y_pred_confidence = tf.convert_to_tensor(y_pred_confidence)

            # Gather all true boxes and classes
            all_true_boxes.append(y_true_boxes)
            all_true_classes.append(y_true_classes)

            # Gather all predicted boxes, classes, and confidence
            all_pred_boxes.append(y_pred_boxes)
            all_pred_classes.append(y_pred_classes)
            if y_pred_confidence is not None:
                all_pred_confidence.append(y_pred_confidence)

        # Concatenate all detections across the batch
        true_boxes_concat = tf.concat(all_true_boxes, axis=0)
        true_classes_concat = tf.concat(all_true_classes, axis=0)
        pred_boxes_concat = tf.concat(all_pred_boxes, axis=0)
        pred_classes_concat = tf.concat(all_pred_classes, axis=0)
        if all_pred_confidence:
            pred_confidence_concat = tf.concat(all_pred_confidence, axis=0)
        else:
            pred_confidence_concat = None

        # Prepare the inputs for the metric
        y_true_padded = {
            "boxes": true_boxes_concat,
            "classes": true_classes_concat,
        }
        y_pred_padded = {
            "boxes": pred_boxes_concat,
            "classes": pred_classes_concat,
        }
        if pred_confidence_concat is not None:
            y_pred_padded["confidence"] = pred_confidence_concat

        # Update the metric
        self.metrics.update_state(y_true_padded, y_pred_padded)

        # Get current metrics
        metrics = self.metrics.result(force=True)
        logs.update(metrics)

        # Save the best model based on mAP
        current_map = metrics.get("MaP", 0)
        if current_map > self.best_map:
            self.best_map = current_map
            self.model.save(self.save_path)

        return logs

yolo.fit(
    train_ds,
    validation_data=val_ds,
    epochs=3,
    callbacks=[EvaluateCOCOMetricsCallback(val_ds, "model.h5")],
)

def visualize_detections(model, dataset, bounding_box_format):
    images, y_true = next(iter(dataset.take(1)))
    y_pred = model.predict(images)
    # Skip the to_ragged conversion if unsupported
    # or manually process y_pred if needed
    # For example, if y_pred is already in the correct format:
    # y_pred = y_pred

    visualization.plot_bounding_box_gallery(
        images,
        value_range=(0, 255),
        bounding_box_format=bounding_box_format,
        y_true=y_true,
        y_pred=y_pred,
        scale=4,
        rows=2,
        cols=2,
        show=True,
        font_scale=0.7,
        class_mapping=class_mapping,
    )

visualize_detections(yolo, dataset=val_ds, bounding_box_format="xyxy")


def compute_iou(boxes1, boxes2):
    """Calcula IoU entre dos conjuntos de cajas (Nx4 y Mx4)."""
    boxes1 = tf.expand_dims(boxes1, 1)  # Nx1x4
    boxes2 = tf.expand_dims(boxes2, 0)  # 1xMx4

    xmin1, ymin1, xmax1, ymax1 = tf.split(boxes1, 4, axis=-1)
    xmin2, ymin2, xmax2, ymax2 = tf.split(boxes2, 4, axis=-1)

    inter_xmin = tf.maximum(xmin1, xmin2)
    inter_ymin = tf.maximum(ymin1, ymin2)
    inter_xmax = tf.minimum(xmax1, xmax2)
    inter_ymax = tf.minimum(ymax1, ymax2)

    inter_area = tf.maximum(0.0, inter_xmax - inter_xmin) * tf.maximum(0.0, inter_ymax - inter_ymin)

    boxes1_area = (xmax1 - xmin1) * (ymax1 - ymin1)
    boxes2_area = (xmax2 - xmin2) * (ymax2 - ymin2)

    union_area = boxes1_area + boxes2_area - inter_area

    iou = inter_area / tf.maximum(union_area, 1e-8)
    return tf.squeeze(iou, axis=-1)  # NxM

def calculate_precision(true_boxes, true_classes, pred_boxes, pred_classes, pred_confidence, iou_threshold=0.5, confidence_threshold=0.5):
    """
    Calcula la precisión para un conjunto de predicciones y etiquetas.
    """
    true_boxes = tf.ragged.to_dense(true_boxes)
    true_classes = tf.ragged.to_dense(true_classes)
    pred_boxes = tf.ragged.to_dense(pred_boxes)
    pred_classes = tf.ragged.to_dense(pred_classes)
    pred_confidence = tf.ragged.to_dense(pred_confidence)


    # Filtrar predicciones por confianza
    mask = pred_confidence >= confidence_threshold
    pred_boxes = tf.boolean_mask(pred_boxes, mask)
    pred_classes = tf.boolean_mask(pred_classes, mask)
    pred_confidence = tf.boolean_mask(pred_confidence, mask)

    tp = 0
    fp = 0
    matched_true_indices = []

    # Para cada predicción, buscar la caja verdadera con mayor IoU
    for i in range(tf.shape(pred_boxes)[0]):
        pred_box = pred_boxes[i]
        pred_class = pred_classes[i]
        # Filtrar verdaderas por clase
        mask_true = true_classes == pred_class
        true_boxes_cls = tf.boolean_mask(true_boxes, mask_true)

        if tf.shape(true_boxes_cls)[0] == 0:
            # No hay cajas verdaderas de esa clase, es FP
            fp += 1
            continue

        ious = compute_iou(tf.expand_dims(pred_box, 0), true_boxes_cls)
        max_iou = tf.reduce_max(ious)
        max_idx = tf.argmax(ious)

        if max_iou >= iou_threshold and max_idx not in matched_true_indices:
            tp += 1
            matched_true_indices.append(max_idx.numpy())
        else:
            fp += 1

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    return precision


# Supongamos que tienes listas de todas las predicciones y etiquetas
all_true_boxes = []
all_true_classes = []
all_pred_boxes = []
all_pred_classes = []
all_pred_confidence = []

# Para cada batch en tu evaluación
for batch in val_ds:
    images, y_true = batch
    y_pred = yolo.predict(images)

    # Extraer datos
    true_boxes = y_true['boxes']
    true_classes = y_true['classes']
    pred_boxes = y_pred['boxes']
    pred_classes = y_pred['classes']
    pred_conf = y_pred.get('confidence', tf.ones_like(pred_boxes[...,0]))

    all_true_boxes.append(true_boxes)
    all_true_classes.append(true_classes)
    all_pred_boxes.append(pred_boxes)
    all_pred_classes.append(pred_classes)
    all_pred_confidence.append(pred_conf)

# Concatenar todos
true_boxes_concat = tf.concat(all_true_boxes, axis=0)
true_classes_concat = tf.concat(all_true_classes, axis=0)
pred_boxes_concat = tf.concat(all_pred_boxes, axis=0)
pred_classes_concat = tf.concat(all_pred_classes, axis=0)
pred_confidence_concat = tf.concat(all_pred_confidence, axis=0)

# Calcular precisión
precision = calculate_precision(
    true_boxes_concat,
    true_classes_concat,
    pred_boxes_concat,
    pred_classes_concat,
    pred_confidence_concat,
    iou_threshold=0.5,
    confidence_threshold=0.5
)
print("Precisión en la evaluación:", precision)





from ultralytics import YOLO
import numpy as np

# Cargar el modelo
model = YOLO('ruta/a/tu/modelo.pt')

# Cargar datos de prueba (por ejemplo, en formato COCO o supervisado)
# Aquí asumiremos que tienes un conjunto de imágenes y sus etiquetas
# Puedes usar el método predict y luego comparar

# Función para calcular precisión en detección
def calculate_detection_precision(model, images, labels, iou_threshold=0.5, conf_threshold=0.25):
    """
    Calcula la precisión en detección para un conjunto de imágenes.
    
    Args:
        model: Modelo YOLOv8 cargado.
        images: Lista de rutas a las imágenes o imágenes en formato numpy array.
        labels: Lista de etiquetas reales en formato compatible.
        iou_threshold: Umbral de IoU para considerar una detección como correcta.
        conf_threshold: Umbral de confianza para filtrar predicciones.
        
    Returns:
        precision: Valor de precisión calculado.
    """
    TP = 0
    FP = 0
    total_gt = 0  # número total de objetos reales
    
    for img_path, gt_labels in zip(images, labels):
        # Realizar predicción
        results = model(img_path, conf=conf_threshold)
        detections = results[0].boxes  # cajas detectadas
        
        # Contar objetos reales
        total_gt += len(gt_labels)
        
        # Convertir detecciones a formato usable
        pred_boxes = []
        pred_scores = []
        pred_classes = []
        for box in detections:
            pred_boxes.append(box.xyxy.cpu().numpy())
            pred_scores.append(box.conf.cpu().numpy())
            pred_classes.append(box.cls.cpu().numpy())
        
        matched_gt = set()
        for pred_box, score, cls in zip(pred_boxes, pred_scores, pred_classes):
            # Buscar si hay una caja real coincidente
            ious = []
            for idx, gt in enumerate(gt_labels):
                if idx in matched_gt:
                    continue
                if gt['class'] == cls:
                    iou = compute_iou(pred_box, gt['bbox'])
                    ious.append((iou, idx))
            if ious:
                max_iou, match_idx = max(ious, key=lambda x: x[0])
                if max_iou >= iou_threshold:
                    TP += 1
                    matched_gt.add(match_idx)
                else:
                    FP += 1
            else:
                FP += 1
                
    precision = TP / (TP + FP) if (TP + FP) > 0 else 0
    return precision

def compute_iou(boxA, boxB):
    # boxA y boxB en formato [xmin, ymin, xmax, ymax]
    xA = max(boxA[0][0], boxB[0])
    yA = max(boxA[0][1], boxB[1])
    xB = min(boxA[2][0], boxB[2])
    yB = min(boxA[2][1], boxB[3])
    interArea = max(0, xB - xA + 1) * max(0, yB - yA + 1)
    boxAArea = (boxA[0][2] - boxA[0][0] + 1) * (boxA[0][3] - boxA[0][1] + 1)
    boxBArea = (boxB[2] - boxB[0] + 1) * (boxB[3] - boxB[1] + 1)
    iou = interArea / float(boxAArea + boxBArea - interArea)
    return iou

# Nota: Necesitarás definir tus propias listas de imágenes y etiquetas.
# Además, debes ajustar los formatos de etiquetas y predicciones a tus datos.






def compute_iou(boxA, boxB):
    """
    Computes the Intersection over Union (IoU) between two bounding boxes.
    Each box is defined by a list or tuple: [xmin, ymin, xmax, ymax].

    Args:
        boxA: List or tuple of 4 numbers.
        boxB: List or tuple of 4 numbers.

    Returns:
        IoU value as a float.
    """
    # Determine the coordinates of the intersection rectangle
    xA = max(boxA[0], boxB[0])
    yA = max(boxA[1], boxB[1])
    xB = min(boxA[2], boxB[2])
    yB = min(boxA[3], boxB[3])

    # Compute the area of intersection rectangle
    inter_width = max(0, xB - xA)
    inter_height = max(0, yB - yA)
    inter_area = inter_width * inter_height

    # Compute the area of both bounding boxes
    boxA_area = (boxA[2] - boxA[0]) * (boxA[3] - boxA[1])
    boxB_area = (boxB[2] - boxB[0]) * (boxB[3] - boxB[1])

    # Compute the IoU
    iou = inter_area / float(boxA_area + boxB_area - inter_area) if (boxA_area + boxB_area - inter_area) != 0 else 0

    return iou

import json

def evaluate_accuracy(model, dataset, iou_threshold=0.5, confidence_threshold=0.5):
   total_true_positives = 0
   total_predictions = 0
   total_objects = 0

   for images, ground_truths in dataset:
        predictions = model.predict(images)
        # Verificar estructura de predictions
        if isinstance(predictions, dict):
            pred_boxes = predictions.get('boxes', [])
            pred_scores = predictions.get('scores', [])
            pred_classes = predictions.get('classes', [])
        elif isinstance(predictions, list):
            # Ajustar según la estructura real
            pred_boxes = [pred['boxes'] for pred in predictions]
            pred_scores = [pred['scores'] for pred in predictions]
            pred_classes = [pred['classes'] for pred in predictions]
        else:
            print(f"Formato desconocido en predicciones: {type(predictions)}")
            continue

        for pred, gt in zip(pred_boxes, ground_truths):
            # Convertir a numpy arrays            
            if isinstance(pred, dict):                              
               pred_boxes_np = np.array(pred['boxes'])
               pred_scores_np = np.array(pred['scores'])
               pred_classes_np = np.array(pred['classes'])
        #gt_value = json.loads(gt['boxes'])
            if isinstance(gt, str):
               if not gt or gt in [None, '', 'None']:
                  print("gt es vacío o None")
                  gt = {}
               else:
                  try:
                     gt = json.loads(gt)
                  except json.JSONDecodeError:
                     print("Error al decodificar gt")
                     gt = {}

            if 'boxes' in gt:
                if isinstance(gt['boxes'], int):
                   try:
                       gt_value = json.loads(gt['boxes'])
                   except json.JSONDecodeError:
                       print("Error al decodificar gt['boxes'] como int")
                       gt_value = []
                elif isinstance(gt['boxes'], list):
                     gt_value = gt['boxes']
                elif isinstance(gt['boxes'], str):
                     if gt['boxes'] and gt['boxes'] != 'None':
                        try:
                          gt_value = json.loads(gt['boxes'])
                        except json.JSONDecodeError:
                           print("Error al decodificar gt['boxes'] como string JSON")
                           gt_value = []
                     else:
                        print("gt['boxes'] está vacía o es 'None'")
                        gt_value = []
                else:
                     print(f"Tipo no esperado en gt['boxes']: {type(gt['boxes'])}")
                     gt_value = []

                print("Estoy imprimiendo", gt_value)
                gt_boxes_np = np.array(gt_value)
                gt_classes_np = np.array(gt['classes'])
            else:
                print("La clave 'boxes' no está en gt")
                gt_boxes_np = []
                gt_classes_np = []
            
            # Contar objetos reales            
            total_objects += len(gt_boxes_np)
           

            mask = pred_scores_np >= confidence_threshold
            pred_boxes_np = pred_boxes_np[mask]
            pred_classes_np = pred_classes_np[mask]
            pred_scores_np = pred_scores_np[mask]

            total_predictions += len(pred_boxes_np)

            # Coincidencias
            for gt_box, gt_class in zip(gt_boxes_np, gt_classes_np):
                matched = False
                for pred_box, pred_class in zip(pred_boxes_np, pred_classes_np):
                    iou = compute_iou(gt_box, pred_box)
                    if iou >= iou_threshold and pred_class == gt_class:
                        matched = True
                        break
                if matched:
                    total_true_positives += 1

   precision = (total_true_positives / total_predictions) if total_predictions > 0 else 0
   recall = (total_true_positives / total_objects) if total_objects > 0 else 0
   print(f'Precision: {precision:.3f}, Recall: {recall:.3f}')
   
evaluate_accuracy(yolo,val_ds)


